<?php
define('API_KEY', 'API key');
define('SHOP_ID', 'Shop ID');
define('FAIL_URL', 'Unsuccessful payment page');
define('SUCCESS_URL', 'Successful payment page');
define('TAX_RATE', 'Tax rate');
define('PAYMENT_TYPE', 'Payment type');
define('CARD_HOLDER', 'Show cardholder on payment form');
define('HOLD_EXPIRATION', 'Write-off at the end of the holding period');
define('RBK', 'RBK Money');
define('RBK_DESCRIPTION', 'RBK Money');
define('ERROR_TAX_RATE_IS_NOT_VALID', 'Invalid value of the tax rate');
define('ERROR_API_KEY_IS_NOT_VALID', 'Invalid value of the `apiKey` parameter');
define('ERROR_SUCCESS_URL_IS_NOT_VALID', 'Invalid value of the `successUrl` parameter');
define('ERROR_FAIL_URL_IS_NOT_VALID', 'Invalid value of the `failUrl` parameter');
define('ERROR_PAYMENT_TYPE_IS_NOT_VALID', 'Invalid value of the `paymentType` parameter');
define('ERROR_HOLD_EXPIRATION_IS_NOT_VALID', 'Invalid value of the `holdExpiration` parameter');
define('PAYMENT_TYPE_HOLD', 'Hold');
define('PAYMENT_TYPE_INSTANTLY', 'Write-off instantly');
define('EXPIRATION_PAYER', 'Payer');
define('EXPIRATION_SHOP', 'Shop');