<?php
define('TRANSACTIONS', 'Transactions');
define('SAVE', 'Save');
define('NEXT', 'Next');
define('PAY', 'Pay');
define('PREVIOUS', 'Previous');
define('WRONG_VALUE', 'Wrong value');
define('WRONG_SIGNATURE', 'Wrong signature');
define('INSTALLATION_SUCCESS', 'Module installation was successful');
define('SETTINGS', 'Settings');
define('RECURRENT', 'Recurrent payments');
define('RECURRENT_ITEMS', 'Items for recurrent payments');
define('API_KEY', 'API key');
define('ITEM_IDS', 'Articles of products for recurrent payments');
define('SHOP_ID', 'Shop ID');
define('SUCCESS_URL', 'Successful payment page');
define('PAYMENT_TYPE', 'Payment type');
define('SHOW_CARD_HOLDER', 'Yes');
define('NOT_SHOW_CARD_HOLDER', 'No');
define('CARD_HOLDER', 'Show cardholder on payment form');
define('HOLD_EXPIRATION', 'Write-off at the end of the holding period');
define('HOLD_STATUS', 'Order status with hold');
define('PROCESSED', 'Processed');
define('PAID', 'Paid');
define('RBK_MONEY', 'RBKmoney');
define('ERROR_SHOP_ID_IS_NOT_VALID', 'Invalid value of the `shopID` parameter');
define('ERROR_API_KEY_IS_NOT_VALID', 'Invalid value of the `apiKey` parameter');
define('ERROR_HOLD_STATUS_IS_NOT_VALID', 'Invalid value of the `holdStatus` parameter');
define('ERROR_SUCCESS_URL_IS_NOT_VALID', 'Invalid value of the `successUrl` parameter');
define('ERROR_PAYMENT_TYPE_IS_NOT_VALID', 'Invalid value of the `paymentType` parameter');
define('ERROR_HOLD_EXPIRATION_IS_NOT_VALID', 'Invalid value of the `holdExpiration` parameter');
define('ERROR_TAX_RATE_IS_NOT_VALID', 'Invalid value `VAT rate` for product: ');
define('PAYMENT_TYPE_HOLD', 'Hold');
define('PAYMENT_TYPE_INSTANTLY', 'Write-off instantly');
define('EXPIRATION_PAYER', 'Payer');
define('EXPIRATION_SHOP', 'Shop');
define('RECURRENT_DELETED', 'Recurrent payment deleted');
define('RBK_MONEY_DATE_FILTER', 'Date');
define('RBK_MONEY_DATE_FILTER_FROM', 'from');
define('RBK_MONEY_DATE_FILTER_TO', 'to');
define('RBK_MONEY_FILTER_SUBMIT', 'Search');
define('RBK_MONEY_TRANSACTION_ID', 'ID');
define('RBK_MONEY_TRANSACTION_PRODUCT', 'Product');
define('RBK_MONEY_TRANSACTION_STATUS', 'Status');
define('RBK_MONEY_TRANSACTION_AMOUNT', 'Amount');
define('RBK_MONEY_TRANSACTION_CREATED_AT', 'Created at');
define('PAYMENT_CONFIRMED', 'Payment confirmed');
define('PAYMENT_CANCELLED', 'Payment cancelled');
define('REFUND_CREATED', 'Payment refund created');
define('PAYMENT_CAPTURE_ERROR', 'Payment confirmation error');
define('PAYMENT_CANCELLED_ERROR', 'Payment cancelled error');
define('REFUND_CREATE_ERROR', 'Refund create error');
define('USER', 'User');
define('AMOUNT', 'Amount');
define('PRODUCT', 'Product');
define('USER_STATUS', 'User status');
define('DELETE', 'Delete');
define('FISCALIZATION', 'Fiscalization (54 Federal Law)');
define('FISCALIZATION_USE', 'Use');
define('FISCALIZATION_NOT_USE', "Don't use");
define('ORDER_PAYMENT', 'Order payment');
define('ORDER_PENDING', 'Your order is pending payment. Go to the');
define('WEBSITE', 'website');
define('STATUS_STARTED', 'started');
define('STATUS_PROCESSED', 'processed');
define('STATUS_CAPTURED', 'captured');
define('STATUS_CANCELLED', 'cancelled');
define('STATUS_CHARGED_BACK', 'charged back');
define('STATUS_REFUNDED', 'refunded');
define('STATUS_FAILED', 'failed');
define('REFUNDED_BY_ADMIN', 'Refunded by admin');
define('CANCELLED_BY_ADMIN', 'Cancelled by admin');
define('CAPTURED_BY_ADMIN', 'Captured by admin');
define('SETTINGS_SAVED', 'Settings saved');
define('CONFIRM_PAYMENT', 'Confirm payment');
define('CANCEL_PAYMENT', 'Cancel payment');
define('CREATE_PAYMENT_REFUND', 'Create payment refund');
define('CUSTOMER_READY', 'Ready');
define('CUSTOMER_UNREADY', 'Unready');
define('RECURRENT_SUCCESS', 'Recurrent payment success: ');