<?php
define('API_KEY', 'API ключ');
define('SHOP_ID', 'ID магазина');
define('FAIL_URL', 'Страница неуспешной оплаты');
define('SUCCESS_URL', 'Страница успешной оплаты');
define('TAX_RATE', 'Ставка налога');
define('CARD_HOLDER', 'Отображение кардхолдера в форме оплаты');
define('PAYMENT_TYPE', 'Тип списания средств');
define('HOLD_EXPIRATION', 'Списание средств по окончанию срока холдирования');
define('RBK', 'RBK Money');
define('RBK_DESCRIPTION', 'RBK Money');
define('ERROR_TAX_RATE_IS_NOT_VALID', 'Некорректное значение ставки налога');
define('ERROR_API_KEY_IS_NOT_VALID', 'Некорректное значение API кюча');
define('ERROR_SUCCESS_URL_IS_NOT_VALID', 'Некорректное значение страницы успешной оплаты');
define('ERROR_FAIL_URL_IS_NOT_VALID', 'Некорректное значение страницы неуспешной оплаты');
define('ERROR_PAYMENT_TYPE_IS_NOT_VALID', 'Некорректное значение типа оплаты');
define('ERROR_HOLD_EXPIRATION_IS_NOT_VALID', 'Некорректное значение стороны списания средств по окончанию срока холдированния');
define('PAYMENT_TYPE_HOLD', 'Холд');
define('PAYMENT_TYPE_INSTANTLY', 'Мгновенное списание');
define('EXPIRATION_PAYER', 'В пользу плательщика');
define('EXPIRATION_SHOP', 'В пользу магазина');